
package vistas;

public class MenuPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form menuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAlumno = new javax.swing.JMenu();
        jmFormAlumno = new javax.swing.JMenuItem();
        jmMateria = new javax.swing.JMenu();
        jmFormMateria = new javax.swing.JMenuItem();
        jmAdministracion = new javax.swing.JMenu();
        jmManejoAdmin = new javax.swing.JMenuItem();
        jmManipulacionNota = new javax.swing.JMenuItem();
        jmConsulta = new javax.swing.JMenu();
        jmAlumnoXMateria = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jmAlumno.setText("Alumno");

        jmFormAlumno.setText("Formulario de Alumno");
        jmFormAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormAlumnoActionPerformed(evt);
            }
        });
        jmAlumno.add(jmFormAlumno);

        jMenuBar1.add(jmAlumno);

        jmMateria.setText("Materia");

        jmFormMateria.setText("Formulario Materia");
        jmFormMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmFormMateriaActionPerformed(evt);
            }
        });
        jmMateria.add(jmFormMateria);

        jMenuBar1.add(jmMateria);

        jmAdministracion.setText("Administración");

        jmManejoAdmin.setText("Manejo de Administracion");
        jmManejoAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManejoAdminActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmManejoAdmin);

        jmManipulacionNota.setText("Manipulacion de Notas");
        jmManipulacionNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmManipulacionNotaActionPerformed(evt);
            }
        });
        jmAdministracion.add(jmManipulacionNota);

        jMenuBar1.add(jmAdministracion);

        jmConsulta.setText("Consultas");

        jmAlumnoXMateria.setText("Alumnos por Materia");
        jmAlumnoXMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlumnoXMateriaActionPerformed(evt);
            }
        });
        jmConsulta.add(jmAlumnoXMateria);

        jMenuBar1.add(jmConsulta);

        jMSalir.setText("Salir");
        jMSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMSalirMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmManejoAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmManejoAdminActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioDeInscripcion fdi = new FormularioDeInscripcion();
        fdi.setVisible(true);
        escritorio.add(fdi);
        escritorio.moveToFront(fdi);
    }//GEN-LAST:event_jmManejoAdminActionPerformed

    private void jmFormAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormAlumnoActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionAlumno gta = new GestionAlumno();
        gta.setVisible(true);
        escritorio.add(gta);
        escritorio.moveToFront(gta);
    }//GEN-LAST:event_jmFormAlumnoActionPerformed

    private void jmFormMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmFormMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        GestionMateria gtm = new GestionMateria();
        gtm.setVisible(true);
        escritorio.add(gtm);
        escritorio.moveToFront(gtm);
    }//GEN-LAST:event_jmFormMateriaActionPerformed

    private void jmManipulacionNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmManipulacionNotaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        CargaDeNotas cdn = new CargaDeNotas();
        cdn.setVisible(true);
        escritorio.add(cdn);
        escritorio.moveToFront(cdn);
    }//GEN-LAST:event_jmManipulacionNotaActionPerformed

    private void jmAlumnoXMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlumnoXMateriaActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        ConsultaAlumnoMateria cam = new ConsultaAlumnoMateria();
        cam.setVisible(true);
        escritorio.add(cam);
        escritorio.moveToFront(cam);
    }//GEN-LAST:event_jmAlumnoXMateriaActionPerformed

    private void jMSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMSalirMouseClicked
        dispose();
    }//GEN-LAST:event_jMSalirMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMSalir;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jmAdministracion;
    private javax.swing.JMenu jmAlumno;
    private javax.swing.JMenuItem jmAlumnoXMateria;
    private javax.swing.JMenu jmConsulta;
    private javax.swing.JMenuItem jmFormAlumno;
    private javax.swing.JMenuItem jmFormMateria;
    private javax.swing.JMenuItem jmManejoAdmin;
    private javax.swing.JMenuItem jmManipulacionNota;
    private javax.swing.JMenu jmMateria;
    // End of variables declaration//GEN-END:variables
}
